### ISSUE TITLE
Can anybody believe this project got SOTA in FVD?

### ISSUE THREAD

**Issue by 20141888** [MAGVIT/magvit#3]
Who can believe it?

**Comment by Lijun-Yu** [comment]
Thank you for raising this question! I apologize for the delay in code release which may potentially fostered this question from you. But I'm also happy to realize that we did something kind of "unbelievable". If you're attending CVPR, we are happy to talk with you during the poster and demo sessions to address any concerns.

As posted in #2, we will provide model checkpoints and generated samples with evaluation scripts to reproduce public benchmark results. It is slow in getting out, but it will finally be there:)

**Comment by xiaobuding888** [comment]
How long will it take
